# Generated by Django 3.1.5 on 2021-01-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('plan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(blank=True, max_length=765, null=True)),
                ('plan_description', models.TextField(blank=True, null=True)),
                ('plan_amount', models.IntegerField(blank=True, null=True)),
                ('plan_added', models.DateTimeField(blank=True, null=True)),
                ('plan_icon', models.CharField(blank=True, max_length=300, null=True)),
                ('plan_type', models.CharField(blank=True, max_length=3, null=True)),
                ('plan_service_id', models.IntegerField(blank=True, null=True)),
                ('plan_gst_amount', models.IntegerField(blank=True, null=True)),
                ('plan_video', models.TextField(blank=True, null=True)),
                ('plan_sample_report', models.TextField(blank=True, null=True)),
                ('plan_original_price', models.IntegerField(blank=True, null=True)),
                ('plan_isactive', models.CharField(blank=True, db_column='plan_isActive', max_length=3, null=True)),
                ('plan_created_by', models.IntegerField(blank=True, null=True)),
                ('plan_updated_date', models.DateTimeField(blank=True, null=True)),
                ('plan_updated_by', models.IntegerField(blank=True, null=True)),
                ('last_modified', models.DateTimeField()),
            ],
            options={
                'db_table': 'plans',
                'managed': False,
            },
        ),
    ]
