# Generated by Django 3.1.5 on 2021-01-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testusers',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('email', models.CharField(db_column='EMAIL', max_length=255)),
                ('username', models.CharField(db_column='USERNAME', max_length=255)),
                ('password', models.CharField(db_column='PASSWORD', max_length=255)),
            ],
            options={
                'db_table': 'TESTUSERS',
                'managed': False,
            },
        ),
    ]
